### PR TITLE
Moved eventnow

### PR DESCRIPTION
**Pull request by H4K0N42**
Moved eventnow out of checkindex so it triggers every cycle
Removed first and last element of appointment_times from eventnow if IGNORE_HARDCODED is True

### CODE REVIEW

**Comment by H4K0N42** [comment]
hopefully fixes #23

**Comment by H4K0N42** [comment]
Please dont merge yet, I have to change something

**Comment by H4K0N42** [comment]
you can merge now :)

**Comment by veebch** [comment]
I've simplified the code as it wasn't working in flipped mode and the flow was becoming complicated. The new version doesn't have any animations (other than the rainbow)

**Comment by H4K0N42** [comment]
> I've simplified the code as it wasn't working in flipped mode and the flow was becoming complicated. The new version doesn't have any animations (other than the rainbow)

I would leave restore and blink in but ok, its your project

**Comment by veebch** [comment]
There are a few good bits that still need to go back in. Your use of the lights for the wifi setup mode is useful and the animations make sense. I'll add them back in once I figure out scheduling. 

I'm looking at using callbacks to prompt the animations, so they happen exactly at the right time, rather than on the closest iteration.

I also looked at webhooks for the calendar changes, but that's a problem for another day.

**Pull request merged**
