### PR TITLE
Added Twocolor mode

### PR DESCRIPTION
**Pull request by H4K0N42**
I could not test the mode yet. Please review and test the code before merging.

### CODE REVIEW

**Comment by H4K0N42** [comment]
I have tested it now and fixed some bugs, you can merge it. @veebch

**Review by veebch — APPROVED** [review]
Looks good!

**Comment by H4K0N42** [comment]
I found a little bug, could you move this one line up to fix it?
image

**Comment by veebch** [comment]
Willdo (and Happy New  Year)!

**Pull request merged**
